import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebarNew: [
        //     {
        //   type: 'category',
        //   label: 'Tutorial',
        //   items: ['tutorial-basics/create-a-document'],
        // },
        {
          type: 'category',
          label: 'Intro Docs',
          collapsible: true,
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'intro-docs' }],
        },
        {
          type: 'category',
          label: 'Design Docs',
          collapsible: true,
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'design-docs' }],
        },
        {
          type: 'category',
          label: 'Compliance Docs',
          collapsible: true,
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'compliance-docs' }],
        },
        {
          type: 'category',
          label: 'Requirement Docs',
          collapsible: true,
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'requirement-docs' }],
        },
      ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;


// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   docsSidebar: [
//         {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//     {
//       type: 'category',
//       label: 'Intro Docs',
//       collapsible: true,
//       collapsed: false,
//       items: [{ type: 'autogenerated', dirName: 'intro-docs' }],
//     },
//     {
//       type: 'category',
//       label: 'Design Docs',
//       collapsible: true,
//       collapsed: false,
//       items: [{ type: 'autogenerated', dirName: 'design-docs' }],
//     },
//     {
//       type: 'category',
//       label: 'Compliance Docs',
//       collapsible: true,
//       collapsed: false,
//       items: [{ type: 'autogenerated', dirName: 'compliance-docs' }],
//     },
//     {
//       type: 'category',
//       label: 'Requirement Docs',
//       collapsible: true,
//       collapsed: false,
//       items: [{ type: 'autogenerated', dirName: 'requirement-docs' }],
//     },
//   ],
// };

// export default sidebars;
