backend:
  name: git-gateway
  branch: main  # Change this to your default branch if it's different

media_folder: "static/img"  # Stores uploaded PDFs and images
public_folder: "/img"  # Public URL for accessing media

collections:
  - name: "intro-docs"
    label: "Intro Docs"
    folder: "docs/intro-docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Upload PDF", name: "pdf", widget: "file", media_library: { allow_multiple: false } }

  - name: "design-docs"
    label: "Design Docs"
    folder: "docs/design-docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Upload PDF", name: "pdf", widget: "file", media_library: { allow_multiple: false } }

  - name: "compliance-docs"
    label: "Compliance Docs"
    folder: "docs/compliance-docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Upload PDF", name: "pdf", widget: "file", media_library: { allow_multiple: false } }

  - name: "requirement-docs"
    label: "Requirement Docs"
    folder: "docs/requirement-docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Upload PDF", name: "pdf", widget: "file", media_library: { allow_multiple: false } }
